# Gebruik de juiste linker voor ARMv7 met GNU libc
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
ar = "arm-linux-gnueabihf-ar"

# Andere ARM targets kunnen nog steeds rust-lld gebruiken als fallback
[target.armv7-unknown-linux-musleabihf]
linker = "rust-lld"

[target.arm-unknown-linux-musleabi]
linker = "rust-lld"

[target.aarch64-unknown-linux-musl]
linker = "rust-lld"
